### ISSUE TITLE
Any login can access any private site

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/craneWeb#16]
Any username is authorized for access to all stations.  This is a significant security issue. 

Expected behavior is that access to a given (non-public) station should only be granted if the username being used is associated with that stations 'ownername' in the userPerm table.  

Current behavior appears to be that any username has access to any non-public station.  

This appears to have been addressed under issue 7 for the magnum site (MagWeb).  So perhaps those changes can be migrated to the crane website as well?

**Comment by Cdetviler** [comment]
It was in fact the same problem that the magweb site faced. I think the issue is fixed now. I tested the following cases:

1. A logged in user cannot access a station page under a different group
2. The general public can only access public stations
3. A logged in user can access public stations
4. A Logged in admin cannot access a station page under a different group
5. A logged in admin can access public stations
6. A logged in user (non-admin) cannot make changes to a station
7. A logged in admin can make changes to a station within their group
8. A logged in admin or user only see stations within their associated groups on the account page
9. A logged in admin or user can access stations within two or more different associated groups.

**Comment by Cdetviler** [comment]
This has been fixed and pulled to the live version.
