### ISSUE TITLE
displayName (Site Title) not shown for password protected sites

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/craneWeb#3]
If a site is password protected, the site title is not shown.  For example, instead of

Highland M16000WA Crane Wind Logger R71
Current Conditions

It would just show:
 Crane Wind Logger R71
Current Conditions

And browser tab just shows "RD Logger WC" instead of the site title.

**Comment by Cdetviler** [comment]
I think I have located why this is happening.

When the page loads, the title is set whether the user has logged in or not. The title is grabbed with this query:

```
SELECT deviceInfo.*, NOW() AS now 
FROM deviceInfo 
WHERE serialNumber='%s' AND public=1
```
This query only retrieves results from entries that are public. Therefore, any 'private' station will be excluded and an empty set will be returned. 

This means that the line in index.php:

```
$head=$title=$deviceInfo["displayName"];
```
will result in the $title variable being empty. Which means that this line in rdHead.php:

```
<title><? echo $title ?> RD Logger WC</title>
```
will display as 'RD Logger WC' because $title is an empty variable. At this point I suspect the fix could be as simple as running a query after successful authentication that looks like:

```
SELECT deviceInfo.*, NOW() AS now 
FROM deviceInfo 
WHERE serialNumber='%s'
```
and then change the $title variable. But I don't know enough about the authentication process right now to know if that would be secure/viable. I have a Separate site set up right now where I can safely make changes and Andrew set me up with a login and password for data.aprsworld

[Here is the link where these changes can be seen](http://data.aprsworld.com/data/crane2/craneWeb/index.php?station_id=R86)

**Comment by Cdetviler** [comment]
I changed the rdHead.php file in my test site so that it queries the database using the following query:

```
SELECT deviceInfo.displayName FROM deviceInfo WHERE serialNumber='%s'
```

This selects the display name from the specified serial number. Then I take the result of that query and set it to the '$head' variable and then I `echo` that variable within the title and h2 tags. The title and header now reflect the actual name of the station.

Currently the function containing the query is in rdHead.php because I didn't want to change worldConfig.php, but it seems that worldConfig.php is eventually where this kind of thing should end up.

**Comment by kb0thn** [comment]
That is the desired behavior. If the station is not publuc, we don't want
unauthorized users to even be able to see the title.

-James Jefferson Jarvis
APRS World, LLC

This message sent from my cell phone. My apologies for brevity and spelling
errors.
On Nov 16, 2015 6:09 PM, "Andrew Kurtz" <notifications@github.com> wrote:

If a site is password protected, the site title is not shown. For example,
instead of

Highland M16000WA Crane Wind Logger R71
Current Conditions

It would just show:
Crane Wind Logger R71
Current Conditions

And browser tab just shows "RD Logger WC" instead of the site title.

—
Reply to this email directly or view it on GitHub
<https://github.com/aprsworld/craneWeb/issues/3>.

**Comment by aprsandrew** [comment]
The current issue is that even authorized users cannot see the site title.  ie, when you log in, with username/password, you still cannot see the site title if the station is not public. 

Regardless, if someone is not logged in, attempting to go to a non-public station takes them to the login screen, so there shouldn't be an issue where they would see the title for a non-public station.

**Comment by aprsandrew** [comment]
Station title on the webpage itself is working correctly.   But it still appears to be showing "RD Logger WC" as the tab title for non-public sites.  

Verified this in both Firefox and Chrome.

**Comment by Cdetviler** [comment]
I have changed this and it is displaying the entirety of the title. in the format:

Surespan "The Bean" - Nova Scotia | Crane Wind Logger R91 Current Conditions
